name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
      

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/test/
          remote_host: 13.233.155.120.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_KEY_AWS }}"
